version: 2

sources:

  - name: github
    schema: github
    tables:
      - name: issue
      - name: issue_assignee
      - name: issue_comment
      - name: issue_label
      - name: label
      - name: user